qmaa: Do not import the non-existent libdebug namespace
libdisplaydebug does not define its own namespace.

error: vendor/qcom/opensource/display/sm8550/qmaa/Android.bp:1:1: module
"soong_namespace": namespace vendor/qcom/opensource/display/sm8550/libdebug
does not exist; Some necessary modules may have been skipped by Soong.
Check if PRODUCT_SOURCE_ROOT_DIRS is pruning necessary Android.bp files.
Did you mean "vendor/qcom/opensource/display/sm8550"?

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>